### ISSUE TITLE
fatal, dkron: failed to establish leadership

### ISSUE THREAD

**Issue by juanpabloaj** [distribworks/dkron#1027]
Hi, I am trying to create a cluster with this docker-compose 

```
ersion: '2'
services:
  dkron:
    hostname: dkron
    image: dkron/dkron
    ports:
      - "8080:8080"
      - "8946"
      - "6868"
    environment:
      - GODEBUG=netdns=go
    command: agent --server --log-level=debug --bootstrap-expect=1
  dkron-server:
    hostname: dkron-server
    image: dkron/dkron
    ports:
      - "8081:8080"
      - "8946"
      - "6868"
    environment:
      - GODEBUG=netdns=go
    command: agent --server --retry-join=dkron:8946 --log-level=debug --bootstrap-expect=3
  dkron-server-2:
    hostname: dkron-server-2
    image: dkron/dkron
    ports:
      - "8082:8080"
      - "8946"
      - "6868"
    environment:
      - GODEBUG=netdns=go
    command: agent --server --retry-join=dkron:8946 --log-level=debug --bootstrap-expect=3
```

I started the containers with 

```
docker-compose up -d
```

I tried to check the behavior of the cluster when I stop two nodes, so I stopped two containers

```
docker-compose stop dkron-server ; docker-compose stop dkron-server-2
```

ok, but when I started those containers again

```
docker-compose up -d dkron-server ; docker-compose up -d dkron-server-2
```

The other container stopped and I saw this message in the logs

```
dkron_1           | time="2021-11-11T14:02:12Z" level=fatal msg="dkron: failed to establish leadership" error="cron is already configured, can not start scheduler" node=dkron
dkron_cluster_dkron_1 exited with code 1
```

am I doing something wrong? 

Any suggestion is welcome. Thanks.
