### ISSUE TITLE
dkron k8s issue

### ISSUE THREAD

**Issue by yxxhero** [distribworks/dkron#1208]
**Describe the bug**
I deployed dkron in the form of StatefulSet in the k8s and found the following problems: the members uri and `dkron raft list-peers` are inconsistent. How should I handle them? It happened after I restarted the pod.

**To Reproduce**

**Expected behavior**

members uri and `dkron raft list-peers` return same info.

**Screenshots**

** Specifications:**
 - OS: [e.g. linux] linux
 - Version [e.g. 2.0.1] 3.2.1

**Additional context**

```yaml
bash-5.1# curl http://localhost:8080/v1/members | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1192  100  1192    0     0  1303k      0 --:--:-- --:--:-- --:--:-- 1164k
[
  {
    "Name": "dkron-server-0",
    "Addr": "172.22.240.240",
    "Port": 8946,
    "Tags": {
      "dc": "dc1",
      "expect": "3",
      "port": "6868",
      "region": "global",
      "role": "dkron",
      "rpc_addr": "172.22.240.240:6868",
      "server": "true",
      "type": "server",
      "version": "3.2.1"
    },
    "Status": 1,
    "ProtocolMin": 1,
    "ProtocolMax": 5,
    "ProtocolCur": 2,
    "DelegateMin": 2,
    "DelegateMax": 5,
    "DelegateCur": 4,
    "id": "0cc35999-a966-a65b-5b0d-89b2ec0c0392",
    "statusText": "alive"
  },
  {
    "Name": "dkron-server-1",
    "Addr": "172.22.240.237",
    "Port": 8946,
    "Tags": {
      "dc": "dc1",
      "expect": "3",
      "port": "6868",
      "region": "global",
      "role": "dkron",
      "rpc_addr": "172.22.240.237:6868",
      "server": "true",
      "type": "server",
      "version": "3.2.1"
    },
    "Status": 1,
    "ProtocolMin": 1,
    "ProtocolMax": 5,
    "ProtocolCur": 2,
    "DelegateMin": 2,
    "DelegateMax": 5,
    "DelegateCur": 4,
    "id": "2f41c88d-7d84-a0ea-71f5-c5c73e287bb7",
    "statusText": "alive"
  },
  {
    "Name": "dkron-server-2",
    "Addr": "172.22.240.236",
    "Port": 8946,
    "Tags": {
      "dc": "dc1",
      "expect": "3",
      "port": "6868",
      "region": "global",
      "role": "dkron",
      "rpc_addr": "172.22.240.236:6868",
      "server": "true",
      "type": "server",
      "version": "3.2.1"
    },
    "Status": 1,
    "ProtocolMin": 1,
    "ProtocolMax": 5,
    "ProtocolCur": 2,
    "DelegateMin": 2,
    "DelegateMax": 5,
    "DelegateCur": 4,
    "id": "2c8ad21d-3bc1-2652-386a-ad57178bdefb",
    "statusText": "alive"
  }
]
```

```bash
bash-5.1# dkron raft list-peers
Node       ID              Address              State     Voter
(unknown)  dkron-server-1  172.22.240.232:6868  follower  true
(unknown)  dkron-server-0  172.22.240.235:6868  follower  true
```
