### ISSUE TITLE
Infinite leadership election brokes job creating

### ISSUE THREAD

**Issue by m-onyshchuk** [distribworks/dkron#1214]
**Describe the bug**
I want to save jobs list after containers restart. Single node version like this:
```
sudo docker run -p 8080:8080 \
--name dkron-test \
-v ~/dkron.data:/dkron.data \
dkron/dkron \
agent --server --data-dir=/dkron.data \
--bootstrap-expect=1 --node-name foo \
--log-level=debug
```
works fine. Next I try to run small two nodes cluster and create job. 

**To Reproduce**
I modified docker-compose.yml from master branch:
```
version: "3"
services:
  node1:
    image: dkron/dkron
    container_name: node1
    ports:
      - "8080:8080"
      - "8946"
      - "6868"
    command: agent --server --bootstrap-expect=1 --data-dir=/dkron.data --node-name node1 --log-level=debug
    volumes:
      - ./dkron-node1.data:/dkron.data
  node2:
    image: dkron/dkron
    container_name: node2
    ports:
      - "8946"
      - "6868"
    command: agent --server --retry-join=node1:8946 --bootstrap-expect=2 --data-dir=/dkron.data --node-name node2 --log-level=debug
    volumes:
      - ./dkron-node2.data:/dkron.data
```
ran docker-compose, next ran job creating:
```
curl -i -d '{"name": "job1","schedule": "@every 10m"}' -H "Content-Type: application/json" -X POST http://localhost:8080/v1/jobs
```
and had got:
```
HTTP/1.1 500 Internal Server Error
X-Whom: node1
```
docker logs snippet:
```
node1    | time="2022-10-26T10:22:46Z" level=info msg="2022-10-26T10:22:46.717Z [ERROR] raft: failed to make requestVote RPC: target=\"{Voter node2 172.18.0.2:6868}\" error=\"dial tcp 172.18.0.2:6868: i/o timeout\" term=391"
node2    | time="2022-10-26T10:22:47Z" level=info msg="2022-10-26T10:22:47.059Z [ERROR] raft: failed to make requestVote RPC: target=\"{Voter node1 172.18.0.3:6868}\" error=\"dial tcp 172.18.0.3:6868: i/o timeout\" term=373"
node1    | time="2022-10-26T10:22:47Z" level=info msg="2022-10-26T10:22:47.518Z [WARN]  raft: Election timeout reached, restarting election"
node1    | time="2022-10-26T10:22:47Z" level=info msg="2022-10-26T10:22:47.518Z [INFO]  raft: entering candidate state: node=\"Node at 172.19.0.3:6868 [Candidate]\" term=411"
node1    | time="2022-10-26T10:22:47Z" level=info msg="2022-10-26T10:22:47.529Z [DEBUG] raft: asking for vote: term=411 from=node2 address=172.18.0.2:6868"
node1    | time="2022-10-26T10:22:47Z" level=info msg="2022-10-26T10:22:47.529Z [DEBUG] raft: voting for self: term=411 id=node1"
node1    | time="2022-10-26T10:22:47Z" level=info msg="2022-10-26T10:22:47.532Z [DEBUG] raft: calculated votes needed: needed=2 term=411"
node1    | time="2022-10-26T10:22:47Z" level=info msg="2022-10-26T10:22:47.532Z [DEBUG] raft: vote granted: from=node1 term=411 tally=1"
node2    | time="2022-10-26T10:22:47Z" level=info msg="2022-10-26T10:22:47.641Z [WARN]  raft: Election timeout reached, restarting election"
node2    | time="2022-10-26T10:22:47Z" level=info msg="2022-10-26T10:22:47.641Z [INFO]  raft: entering candidate state: node=\"Node at 172.19.0.2:6868 [Candidate]\" term=393"
node2    | time="2022-10-26T10:22:47Z" level=info msg="2022-10-26T10:22:47.642Z [DEBUG] raft: voting for self: term=393 id=node2"
node2    | time="2022-10-26T10:22:47Z" level=info msg="2022-10-26T10:22:47.644Z [DEBUG] raft: asking for vote: term=393 from=node1 address=172.18.0.3:6868"
node2    | time="2022-10-26T10:22:47Z" level=info msg="2022-10-26T10:22:47.644Z [DEBUG] raft: calculated votes needed: needed=2 term=393"
node2    | time="2022-10-26T10:22:47Z" level=info msg="2022-10-26T10:22:47.644Z [DEBUG] raft: vote granted: from=node2 term=393 tally=1"
node1    | time="2022-10-26T10:22:48Z" level=error msg="grpc: error dialing." error="context deadline exceeded" method=SetJob node=node1 server_addr=
node1    | time="2022-10-26T10:22:48Z" level=info msg="[GIN] 2022/10/26 - 10:22:48 | 500 | 10.001947762s |      172.19.0.1 | POST     \"/v1/jobs\"" node=node1
```

**Expected behavior**
I think that 500 error is unexpected behavior

**Additional context**
Infinite leadership election as 500 error reason is only my hypothesis. May be my docker-compose.yml is wrong and i will be grateful any suggestions to fix it.

**Comment by vcastellm** [comment]
Try with `bootstrap-expect=2` in both

**Comment by m-onyshchuk** [comment]
I tried it, the result is the same.

**Comment by m-onyshchuk** [comment]
No, previous attempt was without dir clearn up.  
Now I have cleaned dir and reran composition.
Election racing stopped. 
But POST /v1/jobs return 500 response as before.
New logs: 

```
node2    | time="2022-10-26T16:25:15Z" level=info msg="2022-10-26T16:25:15.927Z [INFO]  raft: election won: term=2 tally=2"
node2    | time="2022-10-26T16:25:15Z" level=info msg="2022-10-26T16:25:15.927Z [INFO]  raft: entering leader state: leader=\"Node at 172.19.0.2:6868 [Leader]\""
node2    | time="2022-10-26T16:25:15Z" level=info msg="2022-10-26T16:25:15.927Z [INFO]  raft: added peer, starting replication: peer=node1"
node2    | time="2022-10-26T16:25:15Z" level=info msg="dkron: cluster leadership acquired" node=node2
node2    | time="2022-10-26T16:25:15Z" level=info msg="dkron: monitoring leadership" node=node2
node1    | time="2022-10-26T16:25:15Z" level=info msg="2022-10-26T16:25:15.928Z [WARN]  raft: failed to get previous log: previous-index=1 last-index=0 error=\"log not found\""
node2    | time="2022-10-26T16:25:15Z" level=info msg="2022-10-26T16:25:15.928Z [WARN]  raft: appendEntries rejected, sending older logs: peer=\"{Voter node1 172.19.0.3:6868}\" next=1"
node2    | time="2022-10-26T16:25:15Z" level=info msg="2022-10-26T16:25:15.929Z [INFO]  raft: pipelining replication: peer=\"{Voter node1 172.19.0.3:6868}\""
node2    | time="2022-10-26T16:25:15Z" level=info msg="agent: Starting scheduler" node=node2
node2    | time="2022-10-26T16:25:15Z" level=debug msg="dkron: Skipping self join check since the cluster is too small" node=node2 peer=node2
node1    | time="2022-10-26T16:25:22Z" level=error msg="grpc: error dialing." error="context deadline exceeded" method=SetJob node=node1 server_addr=
node1    | time="2022-10-26T16:25:22Z" level=info msg="[GIN] 2022/10/26 - 16:25:22 | 500 | 10.001299738s |      172.19.0.1 | POST     \"/v1/jobs\"" node=node1
```

**Comment by vcastellm** [comment]
This works for me:

```
version: "3"
services:
  node1:
    image: dkron/dkron
    container_name: node1
    ports:
      - "8080:8080"
      - "8946"
      - "6868"
    command: agent --server --bootstrap-expect=1 --data-dir=/dkron.data --node-name node1 --log-level=debug
    volumes:
      - ./dkron-node1.data:/dkron.data
  node2:
    image: dkron/dkron
    container_name: node2
    ports:
      - "8946"
      - "6868"
    command: agent --server --retry-join=node1:8946 --bootstrap-expect=2 --data-dir=/dkron.data --node-name node2 --log-level=debug
    volumes:
      - ./dkron-node2.data:/dkron.data
```

After cleaning data dirs.

```
node1  | time="2022-10-27T06:26:06Z" level=info msg="dkron: cluster leadership acquired" node=node1
node1  | time="2022-10-27T06:26:06Z" level=info msg="dkron: monitoring leadership" node=node1
node1  | time="2022-10-27T06:26:06Z" level=info msg="agent: Starting scheduler" node=node1
```
