### ISSUE TITLE
RETRY_JOIN fails after server comes back up - it's always DNS!

### ISSUE THREAD

**Issue by fopina** [distribworks/dkron#1253]
**Describe the bug**

After both server and agents are up and cluster is running smoothly, if the server goes down and comes back up with a different IP (but same hostname), agents do not reconnect.

**To Reproduce**

* Use following as `docker-compose.yml`
```
version: '3.7'

x-common: &base
  image: dkron/dkron:3.2.1
  command: agent

networks:
  vpcbr:
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1

services:
  server:
    <<: *base
    environment:
      DKRON_DATA_DIR: /ext/data
      DKRON_SERVER: 1
      DKRON_NODE_NAME: dkron1
      DKRON_BOOTSTRAP_EXPECT: 1
    ports:
      - 8888:8080
    networks:
      vpcbr:
        ipv4_address: 10.5.0.20

  agents:
    <<: *base
    environment:
      DKRON_RETRY_JOIN: server
    networks:
      vpcbr:
    deploy:
      replicas: 3
```
* Wait for everything to be up and running (and http://localhost:8888 shows all 4 nodes in the cluster)
* `docker kill` the server
* Verify that all agents log `level=info msg="removing server dkron1 (Addr: 10.5.0.20:6868) (DC: dc1)" node=...`
* Modify server IP in docker-compose to `10.5.0.22` and run `docker compose up -d` to re-create the server
* Verify that agents never reconnect

**Expected behavior**
Agents would eventually retry joining on hostname, picking up the new IP.

**Additional context**
I understand serf or raft might be tricky with DNS but in this case, server does start up with proper access to data/log, no corruption. And if I restart the agents, they will reconnect just fine.
It seems it's just that retry will go on using IP after first join, instead of re-resolving hostname.

To reproduce the issue, I'm forcing the IP change here, but when running in docker swarm (and I assume in k8s as well) new IP upon service re-creation is expected without using fixed IPs.

Is this something easy to fix?
