### ISSUE TITLE
Dkron can't be used safely used in k8s at the moment

### ISSUE THREAD

**Issue by ivan-kripakov-m10** [distribworks/dkron#1442]
hi!

**Is your feature request related to a problem? Please describe.**
At the moment dkron cannot be safely used in k8s because dkron servers cannot handle IP changes.
To reproduce you can just deploy dkron using [actual helm](https://github.com/distribworks/dkron-helm), shutdown the cluster and redeploy it. 
Nodes will try to reconnect to each other using old IPs, but this process won't succeed.

**Describe the solution you'd like**
I think the consul-like approach can be used: https://github.com/hashicorp/consul/pull/3403

**Additional context**
I'm not sure if this is the only problem with dkron in k8s.
If you know of any other problems, I would suggest making a series of improvements aimed at supporting the work of dkron in k8s.
I think many people would like to have such an opportunity (I have seen many issues that are related to this in one way or another).

**Comment by vcastellm** [comment]
Possibly fixed in https://github.com/distribworks/dkron/pull/1446

**Comment by fopina** [comment]
this looks similar to https://github.com/distribworks/dkron/issues/1253 
is it also fixed by #1446 ? 
Looking forward to update to v4 and test it!

**Comment by vcastellm** [comment]
Hey can you try with v4.0.0-beta? this should be fixed by https://github.com/distribworks/dkron/pull/1446

**Comment by ivan-kripakov-m10** [comment]
Hey, I have already tested #1446 (as I have written in my PR).
Is anybody else is able to set up Dkron in some k8s cluster, I think it will be more sufficient as we will have at the least two evidence that #1446 is a correct change.

**Comment by ivan-kripakov-m10** [comment]
Also there is a significant change in dkron k8s helm. 
https://github.com/distribworks/dkron-helm/pull/7
I tested the build using it. 

@vcastellm are you going to also merge it?

**Comment by ivan-kripakov-m10** [comment]
And also we are for sure waiting for Dkron v4, but isn't it a good idea to release a patch version of Dkron 3.2.x (with #1446) to provide possibility to use Dkron in k8s now?

**Comment by vcastellm** [comment]
@ivan-kripakov-m10 it would be possible to release a patch version for v3 but I don't see any advantage of it. Can you elaborate on possible use cases of v3 vs v4?

**Comment by fopina** [comment]
> Hey can you try with v4.0.0-beta? this should be fixed by #1446

@vcastellm not sure if I'm supposed to use any extra flags but 4.0.0-beta3 does not fix my issue #1253 (which I believe to be similar to this one)

After killing the server (to make it restart), agents report a log like this one

```
## inital join, all good
time="2024-02-11T13:36:59Z" level=info msg="Adding LAN adding server" node=sfpi4 server=dkron1
time="2024-02-11T13:36:59Z" level=info msg="agent: Received event" event=member-update node=pi4

## server (dkron1) killed, and removed from list, never retried
time="2024-02-11T13:49:49Z" level=info msg="agent: Received event" event=member-update node=pi4
time="2024-02-11T13:49:49Z" level=info msg="agent: Received event" event=member-failed node=pi4
time="2024-02-11T13:49:49Z" level=info msg="removing server dkron1 (Addr: 10.0.2.35:6868) (DC: dc1)" node=pi4
```

Docker swarm compose (to illustrate configuration)

```yaml
services:
  server:
    image: dkron/dkron:4.0.0-beta3
    command: agent 
    environment:
      #DKRON_NODE_NAME: "{{.Node.Hostname}}"
      DKRON_NODE_NAME: dkron1
      DKRON_DATA_DIR: /ext/data
      DKRON_SERVER: 1
      DKRON_BIND_ADDR: tasks.server:8946
      DKRON_BOOTSTRAP_EXPECT: 1
    deploy:
      mode: replicated
      replicas: 1
  agents:
    image: dkron/dkron:4.0.0-beta3
    command: agent
    environment:
      DKRON_NODE_NAME: "{{.Node.Hostname}}"
      DKRON_RETRY_JOIN: tasks.server
      DKRON_BIND_ADDR: '{{`{{ GetInterfaceIP "eth0" }}:8946`}}'
      DKRON_TAG: 'arch={{.Node.Platform.Architecture}} server=false'
    deploy:
      mode: global
```
