### ISSUE TITLE
DNS discovery for clustering without hassles

### ISSUE THREAD

**Issue by ProPheT777** [distribworks/dkron#437]
It could be very nice to have DNS discovery to easy reliability. 

A good example in mind, is prometheus, it look likes : 

```
      dns_sd_configs:
        - names:
          - 'tasks.node-exporter'
          type: 'A'
          port: 9100
```

It's supported by orchestrators who use internal DNS, you just have to scale and it's just work. For example here it's a swarm service, where the domain `tasks.<service-name>` is automatically attached to containers which represent a service and work without hassles. Then just do `docker service scale dkron=5` and automatically join the existing dkron cluster. 

What do you think about to have that into dkron ?
