### ISSUE TITLE
error="leadership lost while committing log"

### ISSUE THREAD

**Issue by fopina** [distribworks/dkron#572]
## Steps to Reproduce the Problem

If I start the dkron docker locally such as

```
docker run --rm -v$(pwd)/tmp/:/dbdata/ -p8888:8080 dkron/dkron:v2.0.0-b4 agent --server --bootstrap-expect 1 --data-dir /dbdata/
```

It works. But my deploy environment is on docker swarm and I deploy dkron with this stack:

```
volumes:
  dbdata:

services:
  dkron:
    image: "dkron/dkron:v2.0.0-b4"
    volumes:
      - dbdata:/dbdata/
    environment:
      DKRON_DATA_DIR: /dbdata/
```

(`--server --bootstrap-expect 1` are passed differently in the custom container init script but are still there)

Then I'm unable to create jobs:

```
A 2019-07-13T17:12:10.459230Z ' time="2019-07-13T17:12:10Z" level=info msg="dkron: monitoring leadership" node=0f547ea44628  
A 2019-07-13T17:12:12.156687Z ' time="2019-07-13T17:12:12Z" level=info msg="dkron: cluster leadership acquired" node=0f547ea44628  
A 2019-07-13T17:12:12.157675Z ' time="2019-07-13T17:12:12Z" level=info msg="dkron: monitoring leadership" node=0f547ea44628  
A 2019-07-13T17:12:12.165524Z ' time="2019-07-13T17:12:12Z" level=error msg="dkron: failed to wait for barrier" error="node is not the leader" node=0f547ea44628 
A 2019-07-13T17:12:12.166295Z' time="2019-07-13T17:12:12Z" level=info msg="dkron: cluster leadership lost" node=0f547ea44628  
```

If I remove the volume definition or put the data dir anywhere else it works.

## Specifications

  - Version: 2.0.0-b4
  - Platform: linux
  - Backend store: the only
