### ISSUE TITLE
Facing Issue with tags

### ISSUE THREAD

**Issue by vaibhavfareye** [distribworks/dkron#631]
I am unable to tag the dkron agent by changing the value of tags in dkron.yml file.

My dkron.yml looks like:
```
#Dkron example configuration file
 server: true
 bind-addr: "{{ GetPrivateIP }}:8946"
# log-level: debug
 tags:
   role: rep
# encrypt: a-valid-key-generated-with-dkron-keygen
# retry-join:
#   - provider=aws region=eu-west-1 tag_key=consul tag_value=... access_key_id=... secret_access_key=...
#   - 10.0.0.1
#   - 10.0.0.2
#   - 10.0.0.3
# webhook-url: https://hooks.slack.com/services/XXXXXX/XXXXXXX/XXXXXXXXXXXXXXXXXXXX
# webhook-payload: ""{\"text\":\"A status of {{.JobName}} is {{.Success}}\",\"username\":\"DkronBot\"}""
# webhook-headers:
#   - Content-Type:application/json
# mail-host: email-smtp.eu-west-1.amazonaws.com
# mail-port: 25
# mail-username": mailuser
# mail-password": mailpassword
# mail-from": cron@example.com
# mail-subject-prefix: [Dkron]

```
When i am looking at the dashboard it shows default tags
Please see the screenshot. The 
tags: "role: rep" 
is not getting picked up.

![Screenshot from 2019-11-17 05-20-35](https://user-images.githubusercontent.com/40630109/69000725-3444ed00-08fa-11ea-90bd-d7028b90fc2b.png)

I have installed tried with 2.0.0-rc7 and 2.0.0-rc8. I have installed via rpm file on Amazon Ami
Details of instance:

NAME="Amazon Linux AMI"
VERSION="2017.09"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2017.09"
