### ISSUE TITLE
Leader confiltion when multi node is bootstrap

### ISSUE THREAD

**Issue by pohsiu** [distribworks/dkron#673]
**Describe the bug**
Multi node both in bootstrap mode, can't decide leader. 

```
server1  | time="2020-02-06T01:30:08Z" level=error msg="dkron: 'server1' and 'leader1' are both in bootstrap mode. Only one node should be in bootstrap mode, not adding Raft peer." node=server1
leader1  | time="2020-02-06T01:30:08Z" level=info msg="agent: Received event" event=member-update node=leader1
leader1  | time="2020-02-06T01:30:08Z" level=debug msg="agent: Member event" event=member-update member=leader1 node=leader1
leader1  | time="2020-02-06T01:30:08Z" level=debug msg="agent: Member event" event=member-update member=server1 node=leader1
server1  | time="2020-02-06T01:30:08Z" level=error msg="dkron: 'leader1' and 'server1' are both in bootstrap mode. Only one node should be in bootstrap mode, not adding Raft peer." node=server1
```
**To Reproduce**
docker-compose up
```
version: '2'
services:
  dkron:
    image: dkron/dkron:v2.0.4
    container_name: leader1
    ports:
      - "8080:8080"
      - "6868"
    command: agent --server --bootstrap-expect=1 --log-level=debug --node-name=foo
    volumes:
      - ./datas/leader1/:/opt/local/dkron/dkron.data/
      - ./config/foo.yml:/opt/local/dkron/config/dkron.yml
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
  dkron-server:
    container_name: server1
    image: dkron/dkron:v2.0.4
    ports:
      - "8081:8080"
      - "8946"
      - "6868"
    links:
      - dkron:dkron
    volumes:
      - ./datas/server1/:/opt/local/dkron/dkron.data/
      - ./config/foo2.yml:/opt/local/dkron/config/dkron.yml
    environment:
      - GODEBUG=netdns=go
    command: agent --server --bootstrap-expect=1 --log-level=debug --retry-join=dkron --node-name=foo2
    networks:
      vpcbr:
        ipv4_address: 10.5.0.7
  dkron-server2:
    container_name: server2
    image: dkron/dkron:v2.0.4
    ports:
      - "8082:8080"
      - "8946"
      - "6868"
    links:
      - dkron:dkron
    volumes:
      - ./datas/server2/:/opt/local/dkron/dkron.data/
      - ./config/foo2.yml:/opt/local/dkron/config/dkron.yml
    environment:
      - GODEBUG=netdns=go
    command: agent --server --bootstrap-expect=2 --log-level=debug --retry-join=dkron --node-name=foo22
    networks:
      vpcbr:
        ipv4_address: 10.5.0.9
  dkron-agent:
    container_name: agent1
    image: dkron/dkron:v2.0.4
    ports:
      - "8946"
    links:
      - dkron:dkron
    environment:
      - GODEBUG=netdns=go
    command: agent --retry-join=dkron --log-level=debug --node-name=foo3
    volumes:
      - ./config/foo3.yml:/opt/local/dkron/config/dkron.yml
    networks:
      vpcbr:
        ipv4_address: 10.5.0.8
networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
```

**Expected behavior**
I want to test the condition if leader down, would it re-elect the leader auto.
Reassign the leader after old one left.

**Additional context**
I notice that both of node foo/foo2 regard self as leader, and take node foo22 as follower.
Is that normal??
```
bash-5.0# ./dkron raft list-peers --rpc-addr=10.5.0.6:6868
Node   ID     Address        State     Voter
foo    foo    10.5.0.6:6868  leader    true
foo22  foo22  10.5.0.9:6868  follower  true
bash-5.0# ./dkron raft list-peers --rpc-addr=10.5.0.9:6868
Node   ID     Address        State     Voter
foo    foo    10.5.0.6:6868  follower  true
foo22  foo22  10.5.0.9:6868  follower  true
bash-5.0# ./dkron raft list-peers --rpc-addr=10.5.0.7:6868
Node   ID     Address        State     Voter
foo2   foo2   10.5.0.7:6868  leader    true
foo22  foo22  10.5.0.9:6868  follower  true
```
