### ISSUE TITLE
Kubernetes provisioning example fails

### ISSUE THREAD

**Issue by bittrance** [distribworks/dkron#924]
**Describe the bug**
The [Cloud Auto-join page](https://dkron.io/usage/cloud-auto-join/) for Kubernetes suggests `dkron agent --retry-join "provider=k8s label_selector=\"app=dkron,component=server\""`. However, this command results in cli args parse error message `invalid argument "provider=k8s label_selector=\"app=dkron,component=server\"" for "--retry-join" flag: parse error on line 1, column 28: bare " in non-quoted-field`.

**To Reproduce**
```
func Test_k8sQuotedLabels(t *testing.T) {
	flagset := ConfigFlagSet()
	result := flagset.Parse([]string{"--retry-join", "provider=k8s label_selector=\"foo=bar\""})
	assert.Equal(t, result, nil)
}
```

**Expected behavior**
When trying without quoting, e.g. `label_selector=foo=bar`, dkron log complains
```
ERRO[2021-03-14T23:15:05+01:00] agent: Error Joining                          cluster=LAN error="discover: label_selector: - equals in key's value, enclosing double-quote needed label_selector=\"value-with-=-symbol\"" node=jaron
```
so I would have expected this advise to work.

**Specifications**
Encountered with Docker image  and on master branch at 2b2a2b26e11836fc35f1302811146cbe647232da.

**Additional context**
On researching this, ran into https://github.com/containers/podman/issues/2574 which I believe is a similar issue and suggests which suggests using `StringArray` instead of `StringSlice`. I do not have an easy way to run a locally built container in my Kubernetes cluster, so I can't easily test if that fix fully addresses this issue, just that the parsing test given above turns green with that fix.

**Comment by smullins3000** [comment]
Does anyone know of a fix for this issue? I'm hitting the same problem and can't see a workaround for this.

**Comment by joshniec** [comment]
Yes, I ran into this problem too when trying to pass the options as a CLI argument, instead, I opted to setting my dkron configuration in a `yaml` file, `dkron.yml`. 

For example, my `dkron.yml` file looks something like:
```yaml
server: false
data-dir: /opt/local/dkron
disable-http-tls: true
enable-prometheus: true
log-level: debug
ui: false
retry-join:
  - provider=k8s namespace=dkron label_selector="app=dkron,component=server"
serf-reconnect-timeout: 5s
tags:
  role: agent
  type: worker
```

I use `kustomize`'s `ConfigMapGenerator` to create `ConfigMap` resource, I do this because I also pass in another `yaml` file containing the `slack` processor configuration:
```yaml
configMapGenerator:
  - name: dkron-agent-config
    files:
      - dkron.yml
      - dkron-processor-slack.yml
 ```

And my manifest looks something like this (note: I run dkron agents as a `DaemonSet` on my Kubernetes cluster, and my dkron server as a `StatefulSet`, I use a customized docker container that includes both the dkron binary & kubectl, and the dkron agents execute jobs via `kubectl exec` and some other magic):
```yaml
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dkron-agent
  labels:
    app: dkron
    component: agent
spec:
  selector:
    matchLabels:
      app: dkron
      component: agent
  template:
    metadata:
      labels:
        app: dkron
        component: agent
    spec:
      serviceAccountName: dkron-agent-sa
      volumes:
        - name: dkron-agent-config
          projected:
            sources:
              - configMap:
                  name: dkron-agent-config
      containers:
        - name: dkron-agent
          image: <omitted>
          args:
            - agent
            - --config=/etc/dkron/dkron.yml
          ports:
            - name: http
              containerPort: 80
            - name: grpc
              containerPort: 6868
            - name: serf
              containerPort: 8946
          imagePullPolicy: Always
          volumeMounts:
            - name: dkron-agent-config
              mountPath: /etc/dkron
              readOnly: true
```

I use RBAC resources to control what apis/resources the dkron agents can interact with on the api-server when calling `kubectl`
