### ISSUE TITLE
Add "next" job field to swagger

### ISSUE THREAD

**Issue by FedeBev** [distribworks/dkron#990]
**Is your feature request related to a problem? Please describe.**
I'm generating 

**Describe the solution you'd like**
Simply add the next field to the job definition, it should work out of the box if I'm not mistakeng
```yaml
definitions:
    job:
        .....
        next:
            type: string
            format: date-time
            readOnly: true
            description: "Time of the next job execution"
```

**Additional context**
For my application I generate the client from the swagger definition, and my use case requires to known when the next job execution will be. At the moment I have to patch the swagger file manually and it's a bit annoing
